### ISSUE TITLE
Current SARIF report generation causes problems

### ISSUE THREAD

**Issue by winzj** [mercedes-benz/zap-extensions#5]
With https://github.com/Daimler/zap-extensions/commit/4ed8642dbfecc07426f7a8b49263e9bdd97e6439 I am not able to create a report with the following error.

```
2022-01-17 09:25:16,313 [AWT-EventQueue-0] ERROR TemplateEngine - [THYMELEAF][AWT-EventQueue-0] Exception processing template "/home/jan/.ZAP/reports/sarif-json/report.json": Exception evaluating OGNL expression: "helper.createSupport('sarif',reportData)" (template: "/home/jan/.ZAP/reports/sarif-json/report.json" - line 1, col 13)
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "helper.createSupport('sarif',reportData)" (template: "/home/jan/.ZAP/reports/sarif-json/report.json" - line 1, col 13)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:191) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:95) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.processor.StandardWithTagProcessor.doProcess(StandardWithTagProcessor.java:93) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098) [reports-release-0.10.0.zap:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1067) [reports-release-0.10.0.zap:?]
	at org.zaproxy.addon.reports.ExtensionReports.generateReport(ExtensionReports.java:429) [reports-release-0.10.0.zap:?]
	at org.zaproxy.addon.reports.ReportDialog.save(ReportDialog.java:500) [reports-release-0.10.0.zap:?]
	at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:427) [zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.view.StandardFieldsDialog.access$100(StandardFieldsDialog.java:83) [zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:410) [zap-2.11.1.jar:2.11.1]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) [?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) [?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) [?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) [?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: ognl.MethodFailedException: Method "createSupport" failed for object org.zaproxy.addon.reports.ReportHelper@5e59e7bb
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1932) ~[reports-release-0.10.0.zap:?]
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68) ~[reports-release-0.10.0.zap:?]
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1996) ~[reports-release-0.10.0.zap:?]
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91) ~[reports-release-0.10.0.zap:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[reports-release-0.10.0.zap:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[reports-release-0.10.0.zap:?]
	at ognl.ASTChain.getValueBody(ASTChain.java:141) ~[reports-release-0.10.0.zap:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[reports-release-0.10.0.zap:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[reports-release-0.10.0.zap:?]
	at ognl.Ognl.getValue(Ognl.java:537) ~[reports-release-0.10.0.zap:?]
	at ognl.Ognl.getValue(Ognl.java:501) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.executeExpression(OGNLVariableExpressionEvaluator.java:328) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:170) ~[reports-release-0.10.0.zap:?]
	... 56 more
Caused by: java.lang.NoSuchMethodException: org.zaproxy.addon.reports.ReportHelper.createSupport(java.lang.String, org.zaproxy.addon.reports.ReportData)
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1873) ~[reports-release-0.10.0.zap:?]
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68) ~[reports-release-0.10.0.zap:?]
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1996) ~[reports-release-0.10.0.zap:?]
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91) ~[reports-release-0.10.0.zap:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[reports-release-0.10.0.zap:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[reports-release-0.10.0.zap:?]
	at ognl.ASTChain.getValueBody(ASTChain.java:141) ~[reports-release-0.10.0.zap:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[reports-release-0.10.0.zap:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[reports-release-0.10.0.zap:?]
	at ognl.Ognl.getValue(Ognl.java:537) ~[reports-release-0.10.0.zap:?]
	at ognl.Ognl.getValue(Ognl.java:501) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.executeExpression(OGNLVariableExpressionEvaluator.java:328) ~[reports-release-0.10.0.zap:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:170) ~[reports-release-0.10.0.zap:?]
	... 56 more
```

**Comment by winzj** [comment]
I realised it was an update problem on the filesystem when copying the new version. Closing this issue.
